"use client";

import type { ComplaintStatusMetric, ComplaintTrendMetric, DepartmentReportMetric, EmployeePerformanceMetric, PriorityReportMetric } from "@/types/reports";
import { CHART_COLORS, compliance, orderedTrends, prioritySlices, STATUS_COLORS } from "./report-model";

export function ChartCard({ title, children, action }: { title: string; children: React.ReactNode; action?: React.ReactNode }) {
  return <section className="rounded-2xl border border-line bg-surface p-5 shadow-sm"><header className="flex items-start justify-between gap-3"><h2 className="text-lg font-semibold text-ink">{title}</h2>{action}</header><div className="mt-5">{children}</div></section>;
}

export function EmptyChart({ text }: { text: string }) { return <div className="flex min-h-48 items-center justify-center rounded-xl border border-dashed border-line bg-paper px-5 text-center text-sm text-muted">{text}</div>; }

export function DonutChart({ rows, label, statusLabel }: { rows: Array<{ name: string; value: number; color: string; description?: string }>; label: string; statusLabel?: (status: string) => string }) {
  const visible = rows.filter((row) => row.value > 0); const total = visible.reduce((sum, row) => sum + row.value, 0);
  if (!total) return <EmptyChart text={label} />;
  const radius = 42; const circumference = 2 * Math.PI * radius;
  return <div className="grid items-center gap-5 sm:grid-cols-[10rem_1fr]"><svg viewBox="0 0 120 120" className="mx-auto h-40 w-40" role="img" aria-label={label}><circle cx="60" cy="60" r={radius} fill="none" stroke="#E5E7EB" strokeWidth="18" />{visible.map((row, index) => { const length = (row.value / total) * circumference; const offset = visible.slice(0, index).reduce((sum, previous) => sum + (previous.value / total) * circumference, 0); return <circle key={row.name} cx="60" cy="60" r={radius} fill="none" stroke={row.color} strokeWidth="18" strokeDasharray={`${length} ${circumference - length}`} strokeDashoffset={-offset} transform="rotate(-90 60 60)"><title>{`${statusLabel ? statusLabel(row.name) : row.name}: ${row.value}`}</title></circle>; })}<text x="60" y="57" textAnchor="middle" className="fill-ink text-[17px] font-semibold">{total}</text><text x="60" y="72" textAnchor="middle" className="fill-muted text-[8px]">{label}</text></svg><ul className="space-y-2" aria-label={`${label} legend`}>{visible.map((row) => <li key={row.name} className="flex items-center justify-between gap-3 text-sm"><span className="flex min-w-0 items-center gap-2"><span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: row.color }} /><span className="truncate">{statusLabel ? statusLabel(row.name) : row.name}</span></span><span className="font-semibold text-ink">{row.value} <span className="font-normal text-muted">({Math.round((row.value / total) * 100)}%)</span></span></li>)}</ul></div>;
}

export function StatusDonut({ rows, title, statusLabel, noData }: { rows: ComplaintStatusMetric[]; title: string; statusLabel: (status: string) => string; noData: string }) {
  return <ChartCard title={title}><DonutChart label={noData} statusLabel={statusLabel} rows={rows.map((row) => ({ name: row.status, value: row.count, color: STATUS_COLORS[row.status] }))} /></ChartCard>;
}

export function PriorityDonut({ rows, title, noData }: { rows: PriorityReportMetric[]; title: string; noData: string }) {
  const slices = prioritySlices(rows); return <ChartCard title={title}><DonutChart label={noData} rows={slices.map((row) => ({ name: row.priority.name, value: row.total, color: row.color }))} /></ChartCard>;
}

export function HorizontalBars({ title, rows, metric, metricLabel, noData }: { title: string; rows: DepartmentReportMetric[]; metric: keyof Pick<DepartmentReportMetric, "total" | "open" | "resolved" | "sla_breached">; metricLabel: string; noData: string }) {
  const displayed = [...rows].sort((a, b) => Number(b[metric]) - Number(a[metric])).slice(0, 8); const max = Math.max(...displayed.map((row) => Number(row[metric])), 0);
  return <ChartCard title={title} action={<span className="text-xs text-muted">{metricLabel}</span>}>{max === 0 ? <EmptyChart text={noData} /> : <div className="space-y-4">{displayed.map((row) => <div key={row.department.id}><div className="mb-1 flex justify-between gap-3 text-sm"><span className="truncate text-ink">{row.department.name}</span><strong>{row[metric]}</strong></div><div className="h-2.5 overflow-hidden rounded-full bg-paper"><div className="h-full rounded-full bg-teal" style={{ width: `${(Number(row[metric]) / max) * 100}%` }} /></div></div>)}</div>}</ChartCard>;
}

export function SlaGauge({ title, sla, labels }: { title: string; sla?: { total_with_sla: number; within_sla: number; breached: number; breach_rate: number }; labels: { compliance: string; within: string; breached: string; total: string; noData: string } }) {
  const value = compliance(sla); if (value === null || !sla) return <ChartCard title={title}><EmptyChart text={labels.noData} /></ChartCard>;
  const dash = `${value} ${100 - value}`;
  return <ChartCard title={title}><div className="grid items-center gap-4 sm:grid-cols-[10rem_1fr]"><svg viewBox="0 0 120 120" className="mx-auto h-40 w-40" role="img" aria-label={`${value}% ${labels.compliance}`}><circle cx="60" cy="60" r="44" fill="none" stroke="#E5E7EB" strokeWidth="12" /><circle cx="60" cy="60" r="44" fill="none" stroke={value >= 85 ? "#009199" : value >= 60 ? "#B8862B" : "#A33B2E"} strokeWidth="12" pathLength="100" strokeDasharray={dash} strokeLinecap="round" transform="rotate(-90 60 60)" /><text x="60" y="58" textAnchor="middle" className="fill-ink text-[20px] font-semibold">{value}%</text><text x="60" y="73" textAnchor="middle" className="fill-muted text-[8px]">{labels.compliance}</text></svg><dl className="grid grid-cols-3 gap-2 text-center"><div className="rounded-lg bg-teal/10 p-2"><dt className="text-xs text-muted">{labels.within}</dt><dd className="mt-1 font-semibold text-ink">{sla.within_sla}</dd></div><div className="rounded-lg bg-brick/10 p-2"><dt className="text-xs text-muted">{labels.breached}</dt><dd className="mt-1 font-semibold text-ink">{sla.breached}</dd></div><div className="rounded-lg bg-paper p-2"><dt className="text-xs text-muted">{labels.total}</dt><dd className="mt-1 font-semibold text-ink">{sla.total_with_sla}</dd></div></dl></div></ChartCard>;
}

export function TrendChart({ title, rows, labels, noData }: { title: string; rows: ComplaintTrendMetric[]; labels: { created: string; resolved: string; closed: string; breached: string }; noData: string }) {
  const data = orderedTrends(rows); const max = Math.max(...data.flatMap((row) => [row.created, row.resolved, row.closed, row.sla_breached]), 0); if (!max || !data.length) return <ChartCard title={title}><EmptyChart text={noData} /></ChartCard>;
  const width = 680; const height = 230; const padding = 24; const point = (value: number, index: number) => `${padding + (index * (width - padding * 2)) / Math.max(1, data.length - 1)},${height - padding - (value / max) * (height - padding * 2)}`; const line = (key: keyof ComplaintTrendMetric) => data.map((row, index) => point(Number(row[key]), index)).join(" ");
  const series = [{ key: "created" as const, color: "#009199", label: labels.created }, { key: "resolved" as const, color: "#082248", label: labels.resolved }, { key: "closed" as const, color: "#B8862B", label: labels.closed }, { key: "sla_breached" as const, color: "#A33B2E", label: labels.breached }];
  return <ChartCard title={title}><div className="overflow-x-auto"><svg viewBox={`0 0 ${width} ${height}`} className="h-60 min-w-[34rem] w-full" role="img" aria-label={title}><line x1={padding} x2={width - padding} y1={height - padding} y2={height - padding} stroke="#DCE0E3" />{series.map((item) => <polyline key={item.key} points={line(item.key)} fill="none" stroke={item.color} strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"><title>{item.label}</title></polyline>)}{data.map((row, index) => <text key={row.period} x={padding + (index * (width - padding * 2)) / Math.max(1, data.length - 1)} y={height - 5} textAnchor="middle" className="fill-muted text-[10px]">{row.period.slice(5)}</text>)}</svg></div><div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-xs text-muted">{series.map((item) => <span key={item.key} className="flex items-center gap-1.5"><span className="h-2 w-2 rounded-full" style={{ background: item.color }} />{item.label}</span>)}</div></ChartCard>;
}

export function EmployeeBars({ title, rows, noData, assigned, resolved }: { title: string; rows: EmployeePerformanceMetric[]; noData: string; assigned: string; resolved: string }) {
  const data = [...rows].sort((a, b) => b.assigned_total - a.assigned_total).slice(0, 8); const max = Math.max(...data.map((row) => row.assigned_total), 0); return <ChartCard title={title}>{max === 0 ? <EmptyChart text={noData} /> : <div className="space-y-4">{data.map((row, index) => <div key={row.employee.id}><div className="flex justify-between gap-3 text-sm"><span className="truncate font-medium text-ink">{row.employee.name}</span><span className="text-muted">{row.resolution_rate}%</span></div><div className="mt-1 flex h-3 overflow-hidden rounded-full bg-paper"><span style={{ width: `${(row.assigned_total / max) * 100}%`, backgroundColor: CHART_COLORS[index % CHART_COLORS.length] }} /><span className="bg-teal/45" style={{ width: `${(row.resolved / max) * 100}%` }} /></div><p className="mt-1 text-xs text-muted">{assigned}: {row.assigned_total} · {resolved}: {row.resolved} · SLA: {row.sla_success_rate}%</p></div>)}</div>}</ChartCard>;
}
