"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import Link from "next/link";
import { AlertTriangle, CheckCircle2, Clock3, FileWarning, FolderKanban, Gauge, Users } from "lucide-react";
import { adminEmployeesApi, ApiError, lookupsApi, reportsApi } from "@/lib/api";
import { useLocale } from "@/lib/locale-context";
import { StatusBadge, useStatusLabel } from "@/components/status-badge";
import { Skeleton } from "@/components/ui-feedback";
import type { Category, Department, Employee, Priority } from "@/types/api";
import type { ComplaintStatusMetric, ComplaintTrendMetric, DepartmentReportMetric, EmployeePerformanceMetric, PriorityReportMetric, ReportFilters, ReportOverview, SlaBreachesResponse, SlaPerformanceReport } from "@/types/reports";
import { complaintWorkspaceHref, formatDuration } from "./report-model";
import { ChartCard, EmployeeBars, HorizontalBars, PriorityDonut, SlaGauge, StatusDonut, TrendChart } from "./report-charts";
import { ReportFiltersBar } from "./report-filters";

type ReportKey = "overview" | "status" | "department" | "priority" | "sla" | "employee" | "trends" | "breaches";
type ReportData = { overview: ReportOverview; status: ComplaintStatusMetric[]; department: DepartmentReportMetric[]; priority: PriorityReportMetric[]; sla: SlaPerformanceReport; employee: EmployeePerformanceMetric[]; trends: ComplaintTrendMetric[]; breaches: SlaBreachesResponse & { meta?: { current_page: number; last_page: number; total: number } } };
const INITIAL_FILTERS: ReportFilters = { group_by: "day" };

function displayDate(value: string | null, locale: "ar" | "en") { if (!value || Number.isNaN(new Date(value).getTime())) return "—"; return new Intl.DateTimeFormat(locale === "ar" ? "ar-SY" : "en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)); }
function message(error: unknown, fallback: string) { return error instanceof ApiError ? error.message : fallback; }

function KpiCard({ label, value, hint, icon, tone = "teal" }: { label: string; value: string | number; hint?: string; icon: React.ReactNode; tone?: "teal" | "navy" | "amber" | "brick" }) { const styles = { teal: "bg-teal/10 text-teal", navy: "bg-ink/10 text-ink", amber: "bg-amber/10 text-amber", brick: "bg-brick/10 text-brick" }; return <article className="rounded-2xl border border-line bg-surface p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-medium text-muted">{label}</p><p className="mt-2 text-2xl font-semibold text-ink">{value}</p>{hint && <p className="mt-1 text-xs text-muted">{hint}</p>}</div><span className={`rounded-xl p-2.5 ${styles[tone]}`}>{icon}</span></div></article>; }
function PanelSkeleton() { return <div className="rounded-2xl border border-line bg-surface p-5"><Skeleton className="h-5 w-36" /><Skeleton className="mt-5 h-48 w-full" /></div>; }
function PanelError({ text, retry }: { text: string; retry: () => void }) { return <div className="flex min-h-48 flex-col items-center justify-center gap-3 rounded-xl border border-brick/20 bg-brick/5 p-5 text-center"><AlertTriangle className="h-5 w-5 text-brick" /><p className="text-sm text-brick">{text}</p><button className="text-sm font-semibold text-ink underline" onClick={retry}>Retry</button></div>; }

export function ReportsDashboard() {
  const { t, locale } = useLocale(); const statusLabel = useStatusLabel();
  const [draft, setDraft] = useState<ReportFilters>(INITIAL_FILTERS); const [applied, setApplied] = useState<ReportFilters>(INITIAL_FILTERS); const [data, setData] = useState<Partial<ReportData>>({}); const [errors, setErrors] = useState<Partial<Record<ReportKey, string>>>({}); const [loading, setLoading] = useState<Partial<Record<ReportKey, boolean>>>({});
  const [departments, setDepartments] = useState<Department[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [priorities, setPriorities] = useState<Priority[]>([]); const [employees, setEmployees] = useState<Employee[]>([]); const [departmentMetric, setDepartmentMetric] = useState<"total" | "open" | "resolved" | "sla_breached">("total"); const [breachPage, setBreachPage] = useState(1);
  const version = useRef(0);

  const loadLookups = useCallback(async () => { try { const [departmentResult, categoryResult, priorityResult, employeeResult] = await Promise.all([lookupsApi.departments(), lookupsApi.categories(), lookupsApi.priorities(), adminEmployeesApi.list({ is_active: true, per_page: 100 })]); setDepartments(departmentResult.departments); setCategories(categoryResult.categories); setPriorities(priorityResult.priorities); setEmployees(employeeResult.employees); } catch { /* filters remain usable with date/status controls when lookups are unavailable */ } }, []);

  const loadReports = useCallback(async (filters: ReportFilters, page = 1, only?: ReportKey) => {
    const requestVersion = ++version.current; const keys: ReportKey[] = only ? [only] : ["overview", "status", "department", "priority", "sla", "employee", "trends", "breaches"];
    setLoading((previous) => ({ ...previous, ...Object.fromEntries(keys.map((key) => [key, true])) })); setErrors((previous) => { const next = { ...previous }; keys.forEach((key) => delete next[key]); return next; });
    const callers: Record<ReportKey, () => Promise<ReportData[ReportKey]>> = { overview: () => reportsApi.overview(filters), status: () => reportsApi.complaintsByStatus(filters), department: () => reportsApi.complaintsByDepartment(filters), priority: () => reportsApi.complaintsByPriority(filters), sla: () => reportsApi.slaPerformance(filters), employee: () => reportsApi.employeePerformance(filters), trends: () => reportsApi.complaintTrends(filters), breaches: () => reportsApi.slaBreaches({ ...filters, per_page: 10, page }) };
    const results = await Promise.allSettled(keys.map(async (key) => ({ key, value: await callers[key]() })));
    if (requestVersion !== version.current) return;
    results.forEach((result, index) => { const key = keys[index]; if (result.status === "fulfilled") setData((previous) => ({ ...previous, [result.value.key]: result.value.value })); else setErrors((previous) => ({ ...previous, [key]: message(result.reason, t("reports.dashboard.loadFailed")) })); });
    setLoading((previous) => ({ ...previous, ...Object.fromEntries(keys.map((key) => [key, false])) }));
  }, [t, version]);

  useEffect(() => { const timer = window.setTimeout(() => { void loadLookups(); void loadReports(INITIAL_FILTERS); }, 0); return () => window.clearTimeout(timer); }, [loadLookups, loadReports]);
  const retry = (key: ReportKey) => void loadReports(applied, breachPage, key);
  const apply = () => { setApplied(draft); setBreachPage(1); void loadReports(draft, 1); };
  const reset = () => { setDraft(INITIAL_FILTERS); setApplied(INITIAL_FILTERS); setBreachPage(1); void loadReports(INITIAL_FILTERS, 1); };
  const overview = data.overview;

  return <div className="mx-auto max-w-[92rem] space-y-5"><header className="rounded-2xl bg-ink px-6 py-7 text-white shadow-sm"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-white/65">Balagh · {t("reports.dashboard.insights")}</p><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-3xl font-semibold">{t("reports.title")}</h1><p className="mt-2 text-sm text-white/75">{t("reports.dashboard.subtitle")}</p></div><span className="rounded-full bg-white/10 px-3 py-1.5 text-xs">{t("reports.dashboard.liveData")}</span></div></header>
    <ReportFiltersBar filters={draft} departments={departments} categories={categories} priorities={priorities} employees={employees} busy={Object.values(loading).some(Boolean)} t={t} statusLabel={statusLabel} onChange={setDraft} onApply={apply} onReset={reset} onPreset={(range) => setDraft((previous) => ({ ...previous, ...range }))} />
    {loading.overview ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 7 }).map((_, index) => <PanelSkeleton key={index} />)}</div> : errors.overview ? <PanelError text={errors.overview} retry={() => retry("overview")} /> : overview && <section aria-label={t("reports.dashboard.kpis")} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><KpiCard label={t("reports.dashboard.total")} value={overview.total_complaints} icon={<FolderKanban className="h-5 w-5" />} /><KpiCard label={t("reports.dashboard.open")} value={overview.open_complaints} icon={<FileWarning className="h-5 w-5" />} tone="amber" /><KpiCard label={t("reports.dashboard.resolved")} value={overview.resolved_complaints} icon={<CheckCircle2 className="h-5 w-5" />} /><KpiCard label={t("reports.dashboard.newThisMonth")} value={overview.new_complaints_this_month} hint={`${t("reports.dashboard.today")}: ${overview.new_complaints_today}`} icon={<Users className="h-5 w-5" />} tone="navy" /><KpiCard label={t("reports.dashboard.avgResolution")} value={formatDuration(overview.average_resolution_minutes)} icon={<Clock3 className="h-5 w-5" />} tone="navy" /><KpiCard label={t("reports.dashboard.avgResponse")} value={formatDuration(overview.average_first_response_minutes)} icon={<Gauge className="h-5 w-5" />} tone="teal" /><KpiCard label={t("reports.dashboard.breached")} value={overview.sla_breached_complaints} hint={`${overview.sla_breach_rate}%`} icon={<AlertTriangle className="h-5 w-5" />} tone="brick" /></section>}
    <div className="grid gap-5 xl:grid-cols-3"><div className="xl:col-span-1">{loading.status ? <PanelSkeleton /> : errors.status ? <PanelError text={errors.status} retry={() => retry("status")} /> : <StatusDonut title={t("reports.byStatus")} rows={data.status ?? []} statusLabel={statusLabel} noData={t("reports.dashboard.noData")} />}</div><div className="xl:col-span-1">{loading.department ? <PanelSkeleton /> : errors.department ? <PanelError text={errors.department} retry={() => retry("department")} /> : <HorizontalBars title={t("reports.byDepartment")} rows={data.department ?? []} metric={departmentMetric} metricLabel={t(`reports.dashboard.metric${departmentMetric}`)} noData={t("reports.dashboard.noData")} />}</div><div className="xl:col-span-1">{loading.sla ? <PanelSkeleton /> : errors.sla ? <PanelError text={errors.sla} retry={() => retry("sla")} /> : <SlaGauge title={t("reports.dashboard.slaCompliance")} sla={data.sla} labels={{ compliance: t("reports.dashboard.compliance"), within: t("reports.dashboard.within"), breached: t("reports.dashboard.breached"), total: t("reports.dashboard.total"), noData: t("reports.dashboard.noSla") }} />}</div></div>
    {!loading.department && !errors.department && <div className="flex flex-wrap justify-end gap-2">{(["total", "open", "resolved", "sla_breached"] as const).map((metric) => <button key={metric} onClick={() => setDepartmentMetric(metric)} className={`rounded-full px-3 py-1.5 text-xs font-medium ${departmentMetric === metric ? "bg-ink text-white" : "border border-line bg-surface text-muted"}`}>{t(`reports.dashboard.metric${metric}`)}</button>)}</div>}
    <div className="grid gap-5 xl:grid-cols-3"><div className="xl:col-span-2">{loading.trends ? <PanelSkeleton /> : errors.trends ? <PanelError text={errors.trends} retry={() => retry("trends")} /> : <TrendChart title={t("reports.dashboard.trends")} rows={data.trends ?? []} noData={t("reports.dashboard.noData")} labels={{ created: t("reports.dashboard.created"), resolved: t("reports.dashboard.resolved"), closed: t("reports.dashboard.closed"), breached: t("reports.dashboard.breached") }} />}</div><div>{loading.priority ? <PanelSkeleton /> : errors.priority ? <PanelError text={errors.priority} retry={() => retry("priority")} /> : <PriorityDonut title={t("reports.byPriority")} rows={data.priority ?? []} noData={t("reports.dashboard.noData")} />}</div></div>
    {loading.employee ? <PanelSkeleton /> : errors.employee ? <PanelError text={errors.employee} retry={() => retry("employee")} /> : <EmployeeBars title={t("reports.employeePerformance")} rows={data.employee ?? []} noData={t("reports.dashboard.noData")} assigned={t("reports.dashboard.assigned")} resolved={t("reports.dashboard.resolved")} />}
    <ChartCard title={t("reports.slaBreaches")}>{loading.breaches ? <PanelSkeleton /> : errors.breaches ? <PanelError text={errors.breaches} retry={() => retry("breaches")} /> : <BreachTable rows={data.breaches?.complaints ?? []} locale={locale} t={t} page={data.breaches?.meta?.current_page ?? 1} lastPage={data.breaches?.meta?.last_page ?? 1} onPage={(page) => { setBreachPage(page); void loadReports(applied, page, "breaches"); }} />}</ChartCard>
  </div>;
}

function BreachTable({ rows, locale, t, page, lastPage, onPage }: { rows: NonNullable<ReportData["breaches"]>["complaints"]; locale: "ar" | "en"; t: (path: string) => string; page: number; lastPage: number; onPage: (page: number) => void }) { if (!rows.length) return <p className="py-12 text-center text-sm text-muted">{t("reports.dashboard.noBreaches")}</p>; return <><div className="overflow-x-auto"><table className="w-full min-w-[56rem] text-sm"><thead className="border-b border-line text-start text-xs text-muted"><tr><th className="px-3 py-3 font-medium">{t("reports.dashboard.complaint")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.department")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.priority")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.employee")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.due")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.delay")}</th><th className="px-3 py-3 font-medium">{t("reports.dashboard.status")}</th></tr></thead><tbody>{rows.map((complaint) => <tr key={complaint.id} className="border-b border-line last:border-0 hover:bg-paper"><td className="px-3 py-3"><Link href={complaintWorkspaceHref(complaint.id)} className="block max-w-64 hover:text-teal hover:underline"><span className="block font-semibold text-ink">{complaint.complaint_number}</span><span className="block truncate text-xs text-muted">{complaint.title}</span></Link></td><td className="px-3 py-3 text-muted">{complaint.department?.name ?? "—"}</td><td className="px-3 py-3 text-muted">{complaint.priority?.name ?? "—"}</td><td className="px-3 py-3 text-muted">{complaint.assigned_employee?.name ?? "—"}</td><td className="px-3 py-3 text-muted">{displayDate(complaint.due_at, locale)}</td><td className="px-3 py-3 font-medium text-brick">{formatDuration(complaint.delay_minutes)}</td><td className="px-3 py-3"><StatusBadge status={complaint.status} /></td></tr>)}</tbody></table></div>{lastPage > 1 && <div className="mt-4 flex items-center justify-end gap-3 text-sm"><button disabled={page <= 1} onClick={() => onPage(page - 1)} className="disabled:opacity-40">{t("common.previous")}</button><span className="text-muted">{page} / {lastPage}</span><button disabled={page >= lastPage} onClick={() => onPage(page + 1)} className="disabled:opacity-40">{t("common.next")}</button></div>}</>; }
